[package]
name = "dconf_rs"
license = "MIT"
version = "0.2.1"
authors = ["Kyle Corry <kylecorry31@gmail.com>"]
description = "A Rust API for interacting with dconf."
readme = "README.md"
repository = "https://github.com/kylecorry31/dconf_rs"

[dependencies]
